package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.LimelightHelpers;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    String frontCAM = "limelight-front";

    @SuppressWarnings("unused")
    private double colisionProtect = 1;


    public boolean alinhoAuto = false;

    PIDController headingPID = new PIDController(0.3, 0.0, 0.0);
    {
            headingPID.enableContinuousInput(-180, 180);
            headingPID.setTolerance(2.0);
    }



    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    /**
     * Define o ângulo inicial do robô baseado na aliança.
     * Como o TunerConstants já tem MountPoseYaw(180), aqui usamos a lógica padrão:
     * Red = 180 graus (olhando para o fundo do campo Azul)
     * Blue = 0 graus (olhando para o fundo do campo Vermelho)
     */
    public void configurarAnguloInicial() {
        //pega a aliança da driver station
        var alliance = DriverStation.getAlliance();
        
        // Padrão FRC: Se for Vermelho olha pro Azul (0), se for Azul olha pro Vermelho (180)
        double novoAngulo = (alliance.isPresent() && alliance.get() == Alliance.Red) ? 180.0 : 0.0;

        // 1. A SOLUÇÃO DO FENÓMENO 1: Força o hardware do chip do Pigeon a zerar!
        // Isso faz o Shuffleboard e o Fator de Escala voltarem a ler 0 na mesma hora.
        this.getPigeon2().setYaw(novoAngulo);
        
        // Dá um pequeno fôlego (20ms) para o chip do Pigeon comunicar com os motores
        //para o que o codigo estiver fazendo pelo proximo ciclo de periodic.
        try { Thread.sleep(20); } catch (Exception e) {}

        // 2. Reseta o GPS Virtual (Odometria)
        // reseta a pose de acordo com a aliança. 
        Pose2d poseAtual = this.getState().Pose;
        this.resetPose(new Pose2d(poseAtual.getTranslation(), Rotation2d.fromDegrees(novoAngulo)));
        
        System.out.println("Giroscópio Resetado fisicamente para: " + novoAngulo + " graus");
    }

    @Override
    public void periodic() {
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        double YawRaw = this.getPigeon2().getYaw().getValueAsDouble();
        SmartDashboard.putNumber("Angulo Puro", YawRaw);

        double anguloPigeon = this.getPigeon2().getYaw().getValueAsDouble();

        LimelightHelpers.SetRobotOrientation(frontCAM, anguloPigeon, 0, 0, 0, 0, 0);

        var mt2Front = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(frontCAM);
        // Pega a velocidade de giro do robô (para não confiar na câmera se estivermos girando muito rápido).
        double velocidadeGiro = Math.abs(this.getPigeon2().getAngularVelocityZDevice().getValueAsDouble());

        //se tiver bot pose, tiver um numero de tags superior a 0,
        // a velocidade de giro for menor que 720 dps (graus por segundo)
        // e se a distancia for menor que 4 metros, executa o resto. 
        if (mt2Front != null && mt2Front.tagCount > 0 && velocidadeGiro < 360.0 && mt2Front.avgTagDist < 4.0) {
            
            // --- CÁLCULO DINÂMICO DE CONFIANÇA ---
            double xyStdDev;
            
            if (mt2Front.tagCount >= 2) {
                // Se ver 2 ou mais tags, a MegaTag é absurdamente precisa. Confiança máxima!
                xyStdDev = 0.1; 
            } else {
                // Se ver 1 tag, a confiança diminui conforme a distância aumenta.
                // Ex: A 1 metro = 0.3 (Confia muito). A 3.5 metros = 0.8 (Confia pouco)
                xyStdDev = 0.1 + (mt2Front.avgTagDist * 0.2); 
            }

            this.addVisionMeasurement(
                mt2Front.pose, 
                mt2Front.timestampSeconds,
                VecBuilder.fill(xyStdDev, xyStdDev, 9999999.0)
                //999999 pois da rotação o piegon é o responsavel.
            );
        }

        Pose2d poseAtual = this.getState().Pose;

        SmartDashboard.putNumber("Odometria X", poseAtual.getX());
        SmartDashboard.putNumber("Odometria Y", poseAtual.getY());
        // se verdadeiro retorna o valor estimado, se nao mostra zero
        SmartDashboard.putNumber("Vision X", mt2Front != null ? mt2Front.pose.getX() : 0.0);
        SmartDashboard.putNumber("Vision Y", mt2Front != null ? mt2Front.pose.getY() : 0.0);

        boolean isRed = DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red;
        // decide qual x e y vai ser usado para mirar no Hub, pois o x e y dos elementos e diferente.
        double alvoX = isRed ? 12.05 : 4.6;
        double alvoY = isRed ? 4.03 : 4.03;
        double distanciaHubMetros = Math.hypot(alvoX - poseAtual.getX(), alvoY - poseAtual.getY());


        // pois a arena e como um plano cartesiano. entao se calcula a diferença entre a distancia do hub (tanto x quanto y)
        //depois e feita a conta da hipotenusa com estes valores
        //hipotenusa = raiz quadrada da soma dos dois catetos (diferença de x e y) ao quadrado
        SmartDashboard.putNumber("Distancia HUB (m)", distanciaHubMetros);

        SmartDashboard.putBoolean("Limelight/Visto?", mt2Front != null);
        SmartDashboard.putNumber("Limelight/Tag Count", mt2Front.tagCount);
        SmartDashboard.putNumber("Limelight/Distancia", mt2Front.avgTagDist);
        SmartDashboard.putNumber("Limelight/Pose X", mt2Front.pose.getX());

        NetworkTable table = NetworkTableInstance.getDefault().getTable("limelight-front");

        NetworkTableEntry tx = table.getEntry("tx");
        NetworkTableEntry ty = table.getEntry("ty");
        NetworkTableEntry tv = table.getEntry("tv");

        double x = tx.getDouble(0.0);
        double y = ty.getDouble(0.0);
        double v = tv.getDouble(0.0);

        SmartDashboard.putNumber("Limelight X", x);
        SmartDashboard.putNumber("Limelight Y", y);
        SmartDashboard.putNumber("Alvo Valido (TV)", v);   

    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }


    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public Rotation2d getHeading() {
        return getPose().getRotation();
    }

    public Pose2d getPose() {
        return this.getState().Pose;
    }
        /**
     * "Teletransporta" o X e Y do robô no mapa virtual exatamente para a coordenada 
     * da MegaTag 2, apagando qualquer erro de derrapagem das rodas.
     */
    public void cravarOdometriaNaVisao() {
        //command de correção da odometria no autonomo, pra manter o caminho correto.
        var mt2Front = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(frontCAM);
        double velocidadeGiro = Math.abs(this.getPigeon2().getAngularVelocityZDevice().getValueAsDouble());

        // Só permite o teletransporte se estiver relativamente parado (< 45 deg/s) e perto de uma tag
        if (mt2Front != null && mt2Front.tagCount > 0 && mt2Front.avgTagDist < 3.5 && velocidadeGiro < 45.0) {
            Pose2d poseAtual = this.getState().Pose;
            
            // Cria uma nova pose usando o X e Y perfeitos da câmera, mantendo o ângulo do giroscópio
            Pose2d novaPoseExata = new Pose2d(mt2Front.pose.getTranslation(), poseAtual.getRotation());
            
            this.resetPose(novaPoseExata);
            System.out.println("[VISÃO] Checkpoint Autônomo: Erro das rodas zerado!");
        }
    }

}
